# Generated by Django 4.1.6 on 2023-02-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikesantiago',
            name='empty_slots',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bikesantiago',
            name='free_bikes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bikesantiago',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bikesantiago',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bikesantiago',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
