# Generated by Django 4.1.6 on 2023-02-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bikesantiago_empty_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('typology', models.CharField(max_length=200)),
                ('holder', models.CharField(max_length=200)),
                ('investment', models.CharField(max_length=200)),
                ('date_presentation', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
            ],
        ),
    ]
